### ISSUE TITLE
FeatureRequest: add delay between retries

### ISSUE THREAD

**Issue by dviry** [jabbera/vsts-authenticode#10]
Timestamp servers like [Comodo](https://support.comodo.com/index.php?/Knowledgebase/Article/View/68/0/time-stamping-server) ask politely to "Note: If you are signing several pieces of software with a script, please add a delay of 15 seconds or more between signings so that you're not hammering our servers."

I think it makes sense to add a delay either way between retries, as that might increase the chances of a successful code signing in case of a "bad timing" failure.

Thanks

**Comment by jabbera** [comment]
Hmm, I had no idea. Will take care of this.

**Comment by jabbera** [comment]
Added here: https://github.com/jabbera/vsts-authenticode/commit/df0f13b2f52a8a042c180b7edae0c438e849f264

**Comment by jabbera** [comment]
Released as 2.0.4
