### ISSUE TITLE
FeatureRequest: Append signature

### ISSUE THREAD

**Issue by donig** [jabbera/vsts-authenticode#16]
Could you please add the option to append the signature if one already exists (/as flag)? 

Thank you.

**Comment by jabbera** [comment]
Version 3 has an additional options box where you can add this.

**Comment by donig** [comment]
When will Version 3 be released? Version 2 is the latest in the marketplace.

**Comment by jabbera** [comment]
Sorry, never realized I did not push it. Will do it soon.

**Comment by jabbera** [comment]
All set!

**Comment by donig** [comment]
Thank you - updated to V3 and it works!
