### ISSUE TITLE
Signtool Error because of custom arguments with quotes 

### ISSUE THREAD

**Issue by shabroek** [jabbera/vsts-authenticode#17]
When I fill the box with custom arguments like this::

/d ProgramName /du http://www.example.com

The executed command is:

"D:\Agent17-One\_work\_tasks\authenticode-sign_752fe535-ed47-4c2c-afcf-0778adb0bb12\3.0.0\x64\signtool.exe" sign *other args* "/d ProgramName /du http://www.example.com"

This fails with code: SignTool Error: Invalid option: /d ProgramName /du http://www.example.com

It seems to fail on the " that are generated around the custom arguments.

**Comment by jodykenner** [comment]
Hi there, I am having the same issue with the custom arguments, is there any update on a fix?

**Comment by jabbera** [comment]
Sorry. I just saw these. Please put each param on it's own line.
