### ISSUE TITLE
Multiple additional arguments doesn't work

### ISSUE THREAD

**Issue by dnperfors** [jabbera/vsts-authenticode#21]
I am trying to debug issue #20 by adding the additional arguments `/v /debug` in the additional arguments field, however I get the error: `SignTool Error: Invalid option: /v /debug` because the following is added to the argument list: `"/v /debug"`

**Comment by jabbera** [comment]
It’s a multi line edit. Try putting them on different lines.

**Comment by dnperfors** [comment]
Good point, that is what the description also says... However, I now get the error:
```
2019-03-25T04:28:57.6474265Z SignTool Error: Invalid option: /v
2019-03-25T04:28:57.6477168Z /debug
```

**Comment by jabbera** [comment]
Sigh... I'm splitting on the incorrect character. Can you try v4?

**Comment by dnperfors** [comment]
v4 does fix the issue, thanks
