### ISSUE TITLE
Support specifying the certificate thumbprint (/sha1) to select the signing certificate

### ISSUE THREAD

**Issue by ManuelRin** [jabbera/vsts-authenticode#3]
The latest Task implementation uses the signtool.exe /a command line argument which according to the 
[documenation](https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe) means:

> Automatically selects the best signing certificate. Sign Tool will find all valid certificates that satisfy all 
specified conditions and select the one that is valid for the longest time. lI this option is not present, 
Sign Tool expects to find only one valid signing certificate. 

The current task parameters don't allow to explicitly specify a certificate thumbprint to select a dedicated 
certificate from the store.

Please add an optional parameter (e.g. named "Signing Certificate Thumbprint") which maps to use the 
/sha1 command line argument instead of /a. 

This would be a great enhancement!

All the best, Manuel

**Comment by jabbera** [comment]
Supported in: https://github.com/jabbera/vsts-authenticode/commit/72cc0b2e3897d85511d06b567665873ce2404fea
