### ISSUE TITLE
Have you researched the option to use EV USB Token Certificate

### ISSUE THREAD

**Issue by nikolayyordanov** [jabbera/vsts-authenticode#4]
Currently all CAs are not longer providing file certificates. Is it possible to use your solution with USB Token.

**Comment by jabbera** [comment]
Sorry, I use a self issued cert from in internally trusted CA. I’d be willing to accept a PR though!

**Comment by pavelcf** [comment]
Only EV Code Signing certificates are issued on an USB token. Regular Code Signing certificates are still issued as files. See for example digicert - https://www.digicert.com/code-signing/
And, it is physically not possible to use an USB token with VSTS (i.e. - vsts jobs are running in the cloud, and they do not have access to your local hardware)

**Comment by jabbera** [comment]
@pavelcf if you host the agents on prem it could be possible.
