### ISSUE TITLE
Folder wildcards

### ISSUE THREAD

**Issue by jdholbrook81** [jabbera/vsts-authenticode#5]
I seem to be having challenges with the "Path to files to sign" parameter. The tooltip indicates I can use wildcards, which works fine with wildcards in the file name, but will it handle folders? Consider the example folder structure below:

$(Build.SourcesDirectory)\scripts\MyFolderA\MyScript1.ps1
$(Build.SourcesDirectory)\scripts\MyFolderA\MyScript2.ps1
$(Build.SourcesDirectory)\scripts\MyFolderB\MyScript3.ps1

If I provide the input of: 
`  $(Build.SourcesDirectory)\scripts\MyFolderA\*.ps1 `
The extension will find script 1 and 2. What I'm really looking for is to provide this input:

`$(Build.SourcesDirectory)\scripts\**\*.ps1`

and have the extension find scripts 1,2, and 3. I also tried with a single asterisk for the folder, ie:

`$(Build.SourcesDirectory)\scripts\*\*.ps1`

Workaround is multiple calls to the extension. I'd like to specifiy a root folder and know any scripts placed in subsequent folders will be signed.

Error I get: 
`SignTool Error: File not found: d:\a\1\s\scripts\**\*.ps1
2017-12-12T15:07:26.4454250Z 
2017-12-12T15:07:26.4486353Z Error attempting to sign. Attempt number: 0. Exception text: Error: d:\a\_tasks\authenticode-sign_752fe535-ed47-4c2c-afcf-0778adb0bb12\1.0.0\x64\signtool.exe failed with return code: 1
2017-12-12T15:07:26.4487352Z [command]d:\a\_tasks\authenticode-sign_752fe535-ed47-4c2c-afcf-0778adb0bb12\1.0.0\x64\signtool.exe sign /tr http://timestamp.digicert.com /td sha256 /f d:\a\_temp\mySigningCert.pfx /p ******** /fd sha256 /a d:\a\1\s\scripts\**\*.ps1`

**Comment by dviry** [comment]
Just for reference - what you are looking for is called ["minimatch patterns"](https://docs.microsoft.com/en-us/vsts/build-release/tasks/file-matching-patterns) and it seems this Task currently does not support them.

I'd like too as I could then simply write: **/*.exe

Thanks

**Comment by jabbera** [comment]
I’ll look into this as a substitute for an existing PR.

**Comment by dviry** [comment]
I am assuming it's not supported since it's passing the "Path to files to sign" directly as an argument to signtool.exe which obviously does not support those "minimatch" patterns.... so I am guessing supporting this will become a bigger refactoring.

Thanks

**Comment by jabbera** [comment]
This is supported as minimatch: https://github.com/jabbera/vsts-authenticode/commit/1a522829164e014da6b59c828134e844d2e1112a

**Comment by jabbera** [comment]
Released as 2.0.4

**Comment by jdholbrook81** [comment]
Thank you very much!
