### ISSUE TITLE
FeatureRequest: multiple algos in one go

### ISSUE THREAD

**Issue by dviry** [jabbera/vsts-authenticode#8]
We are signing our .exe files with both SHA1 AND SHA256 (as Microsoft does to all their .EXEs), I currently need to setup 2 Tasks in order to do this - would be a great addition to have them both signed at the same time (maybe a new Algo choice "SHA1 & SHA256").

Thanks

**Comment by jabbera** [comment]
I didn’t know you could even do this. I’ll sort it.

**Comment by jabbera** [comment]
How does the timestamping algo and file algo mix with this? IE: what combinations should be supported?

**Comment by dviry** [comment]
good question - I am just setting either both to SHA1 or to SHA256, it's been working fine so far...

**Comment by jabbera** [comment]
Alright. I can't think of a reason to mix and match so I'm likely to combine the two options into 1 for simplicity.

**Comment by jabbera** [comment]
This turned out to be really invasive compared to all the other work I've done on this task today. I'm not going to implement it, but am happy to take a PR if you find the time.
