### ISSUE TITLE
Bug: "Sign Tool Location" does not work

### ISSUE THREAD

**Issue by dviry** [jabbera/vsts-authenticode#9]
No matter what I enter in the "Sign Tool Location" (under Advanced settings), it always uses it's own local signtool.exe copy.

Thanks

**Comment by jabbera** [comment]
Already found this issue. Will fix.

**Comment by jabbera** [comment]
Fixed: https://github.com/jabbera/vsts-authenticode/commit/2c5e3ecefdd24b278ff6557c64149eb2a8abbab2 

to be released today hopefully

**Comment by jabbera** [comment]
Released as 2.0.4
